#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

data = json.load(sys.stdin)

# Setup default values
orgname = data.get("orgname")
invitations = data.get("invitations")
webvault = data.get("webvault")
websocket = data.get("websocket")
sends = data.get("sends")
emergencyaccess = data.get("emergencyaccess")
icondownload = data.get("icondownload")
signups = data.get("signups")

agent.set_env("OrgName", orgname)
agent.set_env("InvitationsEnabled", invitations)
agent.set_env("WebvaultEnabled", webvault)
agent.set_env("WebsocketEnabled", websocket)
agent.set_env("SendsEnabled", sends)
agent.set_env("EmergencyAccessEnabled", emergencyaccess)
agent.set_env("IconDownloadEnabled", icondownload)
agent.set_env("SignupsEnabled", signups)

# ensure everything is saved to environment
agent.dump_env()
