#!/bin/bash

# create random hex string as admin token for vaultwarden
# adopted from https://github.com/NethServer/ns8-mariadb/blob/main/imageroot/actions/create-module/02create_secrets

set -e

if [[ ! -d ~/.config/state/secrets ]]; then
    /usr/bin/mkdir -p ~/.config/state/secrets
fi

if [[ ! -f ~/.config/state/secrets/passwords.secret ]]; then
    admintoken=$(/usr/bin/openssl rand -hex 27)
    /usr/bin/echo "VAULTWARDEN_ADMINTOKEN=$admintoken
    VAULTWARDEN_ADMINTOKEN=$admintoken" > ~/.config/state/secrets/passwords.secret
fi
