#!/bin/bash

# create random hex string as admin token for vaultwarden
# adopted from https://github.com/NethServer/ns8-mariadb/blob/main/imageroot/actions/create-module/02create_secrets

set -e

if [[ ! -d ~/.config/state/secrets ]]; then
    /usr/bin/mkdir -p ~/.config/state/secrets
    /usr/bin/echo 'created directory ~/.config/state/secrets'
fi

if [[ ! -f ~/.config/state/secrets/passwords.secret ]]; then
    /usr/bin/echo 'creating random admintoken'
    admintoken=$(/usr/bin/openssl rand -hex 27)
    /usr/bin/echo "VAULTWARDEN_ADMINTOKEN=$admintoken" > ~/.config/state/secrets/passwords.secret
    /usr/bin/echo 'admintoken saved'
fi
